UsuariosAPI/UsuariosAPI/Controllers/SucursalesController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;
using UsuariosAPI.Models.ViewModels;
using UsuariosAPI.Models;

namespace UsuariosAPI.Controllers
{
	public class SucursalesController : Controller
	{
		private readonly DatosUsuarioContext _context;
		private readonly IHttpClientFactory _httpClientFactory;

		public SucursalesController(DatosUsuarioContext context, IHttpClientFactory httpClientFactory)
		{
			_context = context;
			_httpClientFactory = httpClientFactory;
		}

		public async Task<IActionResult> Index()
		{
			try
			{
				var cliente = _httpClientFactory.CreateClient("ApiClient");
				var respuesta_sucursales = await cliente.GetAsync("api/ApiSucursales");
				var json_sucursales = await respuesta_sucursales.Content.ReadAsStringAsync();
				Response.StatusCode = (int)respuesta_sucursales.StatusCode;
				if (!respuesta_sucursales.IsSuccessStatusCode)
				{
					var error = JsonConvert.DeserializeObject<ValidationProblemDetails>(json_sucursales);
					Response.StatusCode = (int)error.Status;
					ViewData["errors"] = error.Errors;
					return View();
				}

				return View(JsonConvert.DeserializeObject<List<SucursalViewModel>>(json_sucursales));
			}
			catch (Exception)
			{
				Response.StatusCode = 500;
				ViewData["errors"] = new Dictionary<string, string[]>
							{
								{ "ErrorServidor", new[] { "Error con el servidor" } }
							};
			}
			return View();
		}

        public async Task<IActionResult> Agregar()
        {
            return View();
        }

        [HttpPost]
		public async Task<IActionResult> Agregar(SucursalViewModel sucursalViewModel)
		{
			try
			{
				if (ModelState.IsValid)
				{
					var cliente = _httpClientFactory.CreateClient("ApiClient");
					var contenido = new StringContent(JsonConvert.SerializeObject(sucursalViewModel), Encoding.UTF8, "application/json");
					var respuesta_sucursales = await cliente.PostAsync("api/ApiSucursales", contenido);
					var json_sucursales = await respuesta_sucursales.Content.ReadAsStringAsync();
					Response.StatusCode = (int)respuesta_sucursales.StatusCode;
					if (!respuesta_sucursales.IsSuccessStatusCode)
					{
						var error = JsonConvert.DeserializeObject<ValidationProblemDetails>(json_sucursales);
						Response.StatusCode = (int)error.Status;
						ViewData["errors"] = error.Errors;
						return View();
					}
					return RedirectToAction(nameof(Index));
				}

				return View();
			}
			catch (Exception)
			{
				Response.StatusCode = 500;
				ViewData["errors"] = new Dictionary<string, string[]>
							{
								{ "ErrorServidor", new[] { "Error con el servidor" } }
							};
			}
			return View();
		}

		[HttpGet]
		public async Task<IActionResult> Editar(uint id)
		{
			try
			{
				var cliente = _httpClientFactory.CreateClient("ApiClient");

				var respuesta_sucursales = await cliente.GetAsync("api/ApiSucursales/" + id);
				var json_sucursales = await respuesta_sucursales.Content.ReadAsStringAsync();
				Response.StatusCode = (int)respuesta_sucursales.StatusCode;
				if (!respuesta_sucursales.IsSuccessStatusCode)
				{
					var error = JsonConvert.DeserializeObject<ValidationProblemDetails>(json_sucursales);
					Response.StatusCode = (int)error.Status;
					ViewData["errors"] = error.Errors;
					return View();
				}

				var sucursales = JsonConvert.DeserializeObject<SucursalViewModel>(json_sucursales);
				if (sucursales == null)
				{
					Response.StatusCode = 400;
					ViewData["errors"] = new Dictionary<string, string[]>
							{
								{ "ErrorServidor", new[] { "La sucursal no existe" } }
							};

					return View();
				}

				return View(sucursales);
			}
			catch (Exception)
			{
				Response.StatusCode = 500;
				ViewData["errors"] = new Dictionary<string, string[]>
							{
								{ "ErrorServidor", new[] { "Error con el servidor" } }
							};
			}
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> Editar(uint id, SucursalViewModel sucursalViewModel)
		{
			try
			{
				if (ModelState.IsValid)
				{
					var cliente = _httpClientFactory.CreateClient("ApiClient");
					var contenido = new StringContent(JsonConvert.SerializeObject(sucursalViewModel), Encoding.UTF8, "application/json");
					var respuesta_put = await cliente.PutAsync("api/ApiSucursales/" + id, contenido);
					var json_put = await respuesta_put.Content.ReadAsStringAsync();
					Response.StatusCode = (int)respuesta_put.StatusCode;
					if (!respuesta_put.IsSuccessStatusCode)
					{
						var error = JsonConvert.DeserializeObject<ValidationProblemDetails>(json_put);
						Response.StatusCode = (int)error.Status;
						ViewData["errors"] = error.Errors;
						return View();
					}
					return RedirectToAction(nameof(Index));
				}

				return View(sucursalViewModel);
			}
			catch (Exception)
			{
				Response.StatusCode = 500;
				ViewData["errors"] = new Dictionary<string, string[]>
							{
								{ "ErrorServidor", new[] { "Error con el servidor" } }
							};
			}
			return View();
		}

		public async Task<IActionResult> Eliminar(uint id)
		{
			try
			{
				var cliente = _httpClientFactory.CreateClient("ApiClient");
				var respuesta = await cliente.DeleteAsync("api/ApiSucursales/" + id);
				var json = await respuesta.Content.ReadAsStringAsync();
				Response.StatusCode = (int)respuesta.StatusCode;
				if (!respuesta.IsSuccessStatusCode)
				{
					var error = JsonConvert.DeserializeObject<ValidationProblemDetails>(json);
					Response.StatusCode = (int)error.Status;
					ViewData["errors"] = error.Errors;
					return View();
				}
				return RedirectToAction(nameof(Index));
			}
			catch (Exception)
			{
				Response.StatusCode = 500;
				ViewData["errors"] = new Dictionary<string, string[]>
							{
								{ "ErrorServidor", new[] { "Error con el servidor" } }
							};
			}
			return View();
		}

	}
}

UsuariosAPI/UsuariosAPI/Views/Sucursales/Agregar.cshtml
@using UsuariosAPI.Models.ViewModels
@model SucursalViewModel

<div class="text-danger">
	@if (Context.Response.StatusCode >= 400)
	{
		@foreach (var kvp in (Dictionary<string, string[]>)ViewBag.errors)
		{
			@foreach (var value in kvp.Value)
			{
				<p>
					@Html.DisplayFor(m => value)
				</p>
			}
		}
	}
</div>

<form asp-action="Agregar">
	<div asp-validation-summary="ModelOnly" class="text-danger"></div>
	<div class="mt-3">
		<label asp-for="Id" class="form-label"></label>
		<input asp-for="Id" class="form-control" value="0"></input>
		<span asp-validation-for="Id" class="text-danger"></span>
	</div>
	<div class="mt-3">
		<label asp-for="Nombre" class="form-label"></label>
		<input asp-for="Nombre" class="form-control"></input>
		<span asp-validation-for="Nombre" class="text-danger"></span>
	</div>
	<div class="mt-3">
		<input type="submit" value="Agregar" class="btn btn-success" />
	</div>
</form>

UsuariosAPI/UsuariosAPI/Views/Sucursales/Editar.cshtml
@using UsuariosAPI.Models.ViewModels
@model SucursalViewModel

<div class="text-danger">
	@if (Context.Response.StatusCode >= 400)
	{
		@foreach (var kvp in (Dictionary<string, string[]>)ViewBag.errors)
		{
			@foreach (var value in kvp.Value)
			{
				<p>
					@Html.DisplayFor(m => value)
				</p>
			}
		}
	}
</div>

<form asp-action="Editar">
	<div asp-validation-summary="ModelOnly" class="text-danger"></div>
	<div class="mt-3">
		<label asp-for="Id" class="form-label"></label>
		<input asp-for="Id" class="form-control"></input>
		<span asp-validation-for="Id" class="text-danger"></span>
	</div>
	<div class="mt-3">
		<label asp-for="Nombre" class="form-label"></label>
		<input asp-for="Nombre" class="form-control"></input>
		<span asp-validation-for="Nombre" class="text-danger"></span>
	</div>
	<div class="mt-3">
		<input type="submit" value="Editar" class="btn btn-warning" />
	</div>
</form>

UsuariosAPI/UsuariosAPI/Views/Sucursales/Eliminar.cshtml
<h1 class="text-danger">
	@if (Context.Response.StatusCode >= 400)
	{
		@foreach (var kvp in (Dictionary<string, string[]>)ViewBag.errors)
		{
			@foreach (var value in kvp.Value)
			{
				<p>
					@Html.DisplayFor(m => value)
				</p>
			}
		}
	}
</h1>

UsuariosAPI/UsuariosAPI/Views/Sucursales/Index.cshtml
@using UsuariosAPI.Models.ViewModels
@model List<SucursalViewModel>

<h1>Sucursales</h1>

<a class="btn btn-success" asp-controller="Sucursales" asp-action="Agregar">Agregar</a>

<table class="table">
	<thead>
		<tr>
			<th>Id</th>
			<th>Nombre</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@if (Context.Response.StatusCode <= 299 && Context.Response.StatusCode >= 200)
		{
			@foreach (var sucursal in Model)
			{
				<tr>
					<td>@Html.DisplayFor(m => sucursal.Id)</td>
					<td>@Html.DisplayFor(m => sucursal.Nombre)</td>
					<td>
						<a asp-controller="Sucursales" asp-action="Editar" asp-route-id="@sucursal.Id" class="btn btn-warning">Editar</a>
						<a asp-controller="Sucursales" asp-action="Eliminar" asp-route-id="@sucursal.Id" class="btn btn-danger">Eliminar</a>
					</td>
				</tr>
			}
		}
		else
		{
			<div class="text-danger">

				@foreach (var kvp in (Dictionary<string, string[]>)ViewBag.errors)
				{
					@foreach (var value in kvp.Value)
					{
						<p>
							@Html.DisplayFor(m => value)
						</p>
					}
				}

			</div>
		}
	</tbody>
</table>